-- Create companyNotes table (mirroring contactNotes structure)
CREATE TABLE "public"."companyNotes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "company_id" BIGINT NOT NULL,
    "text" TEXT,
    "date" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "sales_id" BIGINT,
    "status" TEXT,
    "attachments" JSONB[]
);

-- Enable RLS
ALTER TABLE "public"."companyNotes" ENABLE ROW LEVEL SECURITY;

-- Primary key
CREATE UNIQUE INDEX "companyNotes_pkey" ON "public"."companyNotes" USING btree (id);
ALTER TABLE "public"."companyNotes" ADD CONSTRAINT "companyNotes_pkey" PRIMARY KEY USING INDEX "companyNotes_pkey";

-- Foreign keys
ALTER TABLE "public"."companyNotes" 
ADD CONSTRAINT "companyNotes_company_id_fkey" 
FOREIGN KEY (company_id) REFERENCES companies(id) 
ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."companyNotes" 
VALIDATE CONSTRAINT "companyNotes_company_id_fkey";

ALTER TABLE "public"."companyNotes" 
ADD CONSTRAINT "companyNotes_sales_id_fkey" 
FOREIGN KEY (sales_id) REFERENCES sales(id) NOT VALID;

ALTER TABLE "public"."companyNotes" 
VALIDATE CONSTRAINT "companyNotes_sales_id_fkey";

-- Grants
GRANT DELETE ON TABLE "public"."companyNotes" TO "authenticated";
GRANT INSERT ON TABLE "public"."companyNotes" TO "authenticated";
GRANT SELECT ON TABLE "public"."companyNotes" TO "authenticated";
GRANT UPDATE ON TABLE "public"."companyNotes" TO "authenticated";

GRANT DELETE ON TABLE "public"."companyNotes" TO "service_role";
GRANT INSERT ON TABLE "public"."companyNotes" TO "service_role";
GRANT REFERENCES ON TABLE "public"."companyNotes" TO "service_role";
GRANT SELECT ON TABLE "public"."companyNotes" TO "service_role";
GRANT TRIGGER ON TABLE "public"."companyNotes" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."companyNotes" TO "service_role";
GRANT UPDATE ON TABLE "public"."companyNotes" TO "service_role";

-- RLS Policies (mirror contactNotes policies)
CREATE POLICY "Enable insert for authenticated users only"
ON "public"."companyNotes"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable read access for authenticated users"
ON "public"."companyNotes"
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Company Notes Delete Policy"
ON "public"."companyNotes"
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Company Notes Update Policy"
ON "public"."companyNotes"
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (true);

-- Full-text search index
CREATE INDEX IF NOT EXISTS idx_company_notes_fts
ON "companyNotes" USING gin(to_tsvector('english', COALESCE(text, '')));

-- Trigram index for fuzzy matching
CREATE INDEX IF NOT EXISTS idx_company_notes_trgm
ON "companyNotes" USING gin(COALESCE(text, '') gin_trgm_ops);

