-- Create manual_discounts table (similar to tags)
create table "public"."manual_discounts" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "color" text not null
);

alter table "public"."manual_discounts" enable row level security;

CREATE UNIQUE INDEX manual_discounts_pkey ON public.manual_discounts USING btree (id);

alter table "public"."manual_discounts" add constraint "manual_discounts_pkey" PRIMARY KEY using index "manual_discounts_pkey";

-- Add manual_discount_ids array field to contacts table
ALTER TABLE contacts ADD COLUMN "manual_discount_ids" bigint[];

-- Create index for array searches
CREATE INDEX contacts_manual_discount_ids_idx ON contacts USING GIN (manual_discount_ids);

-- Grant permissions (similar to tags)
grant delete on table "public"."manual_discounts" to "authenticated";
grant insert on table "public"."manual_discounts" to "authenticated";
grant references on table "public"."manual_discounts" to "authenticated";
grant select on table "public"."manual_discounts" to "authenticated";
grant trigger on table "public"."manual_discounts" to "authenticated";
grant update on table "public"."manual_discounts" to "authenticated";

-- Create RLS policies (similar to tags)
create policy "Enable delete for authenticated users only"
on "public"."manual_discounts"
as permissive
for delete
to authenticated
using (true);

create policy "Enable update for authenticated users only"
on "public"."manual_discounts"
as permissive
for update
to authenticated
using (true);

create policy "Enable insert for authenticated users only"
on "public"."manual_discounts"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable read access for authenticated users"
on "public"."manual_discounts"
as permissive
for select
to authenticated
using (true);

